PR Test_1
Tihorez/Ftracker_Next_5 pull request #1
Opened 2024-07-31 23:37 UTC by Tihorez

2024-08-01 19:48 UTC, dirtymew requested changes
Привет Тихон

хорошая работа - но есть одна ошибка которую нужно поправить

2024-08-01 19:48 UTC, dirtymew commented on .idea/.gitignore
> +/shelf/
это все лучше в .gitignore

2024-08-01 19:48 UTC, dirtymew commented on main.go
> +	return InfoMessage{t.TrainingType, t.Duration,
тут все ок- если у структуры много полей - то лучше так 

```
InfoMessage{
  TrainingType: t.TrainingType,
  Duration: t.Duration,
...
}
```

читать проще

2024-08-01 19:48 UTC, dirtymew commented on main.go
> +	info.Calories = r.Calories()
тут в целом ок - хоть немного не по заданию

2024-08-01 19:48 UTC, dirtymew commented on main.go
> +	info := s.Training.TrainingInfo()
тут можно и так но по заданию и в целом проще структуру заново инициализировать

2024-08-01 19:48 UTC, dirtymew commented on main.go
> +		w.Height)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
тут ошибка в формуле - проверь что все переменные использовал

2024-08-03 15:27 UTC, Tihorez commented on .idea/.gitignore
> +/shelf/
Привет, Антон
И откуда это берется? В ide goland все чисто

2024-08-03 15:56 UTC, Tihorez commented on main.go
> +	return InfoMessage{t.TrainingType, t.Duration,
Пробывал так менять, компилятор сразу выдает кучу ошибок

2024-08-03 16:10 UTC, Tihorez commented on main.go
> +		w.Height)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
поправил

2024-08-04 07:33 UTC, dirtymew commented on .idea/.gitignore
> +/shelf/
это она и генерит - а еще одна предлагает добавить в проект файл .gitignore

2024-08-04 07:34 UTC, dirtymew commented on main.go
> +	return InfoMessage{t.TrainingType, t.Duration,
что-то не то ты делаешь - никаких ошибок компилятор не выдаст это стандартный способ описание структур
```
func TrainingInfo() InfoMessage {
	return InfoMessage{
		TrainingType: t.TrainingType,
		Duration:     t.Duration,
		Distance:     t.distance(),
		Speed:        t.meanSpeed(),
		Calories:     t.Calories(),
	}
}

```

2024-08-04 07:40 UTC, dirtymew approved these changes
Привет Тихон

зачет

2024-08-04 12:33 UTC, Tihorez commented on main.go
> +	return InfoMessage{t.TrainingType, t.Duration,
спасибо, пересмотрю

2024-08-21 11:53 UTC, merged